kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kafka-cluster
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 30950
    hostPort: 7070
  - containerPort: 30960
    hostPort: 7080
- role: worker
  extraPortMappings:
  - containerPort: 30951
    hostPort: 7071
  - containerPort: 30961
    hostPort: 7081
- role: worker
  extraPortMappings:
  - containerPort: 30952
    hostPort: 7072
  - containerPort: 30962
    hostPort: 7082
