kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kafka-cluster
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 30950
    hostPort: 7070
- role: worker
  extraPortMappings:
  - containerPort: 30951
    hostPort: 7071
- role: worker
  extraPortMappings:
  - containerPort: 30952
    hostPort: 7072
